/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.school.views;

import com.school.models.Student;
import com.school.models.Course;
import com.school.models.Note;
import com.school.services.StudentService;
import com.school.services.EnrollmentService;
import com.school.services.CourseService;
import com.school.services.NoteService;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EliteBook
 */
public class Enrollments extends javax.swing.JFrame {

    public static int roleId;

    /**
     * Creates new form Enrollments
     */
    public Enrollments() {
        initComponents();
        tbDataCourses.setModel(new DefaultTableModel());
        tbDataEnrollments.setModel(new DefaultTableModel());

        lblStudentIdAdd.setVisible(false);
        lblCourseIdAdd.setVisible(false);
        lblEnrollmentId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblStudentCode = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        lblStudentFullName = new javax.swing.JLabel();
        lblStudentFullNameAdd = new javax.swing.JLabel();
        lblStudentEnrollmentDate = new javax.swing.JLabel();
        lblStudentEnrollmentDateAdd = new javax.swing.JLabel();
        btnStudentSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDataEnrollments = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDataCourses = new javax.swing.JTable();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        lblCourseTitleAdd = new javax.swing.JLabel();
        lblCourseTitle = new javax.swing.JLabel();
        btnCourseAdd = new javax.swing.JButton();
        btnCourseRemove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblCourseIdAdd = new javax.swing.JLabel();
        lblStudentIdAdd = new javax.swing.JLabel();
        lblEnrollmentId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Matriculas");
        lblTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblStudentCode.setText("Código:");

        lblStudentFullName.setText("Nombre completo:");

        lblStudentFullNameAdd.setText("-");

        lblStudentEnrollmentDate.setText("Fecha registro:");

        lblStudentEnrollmentDateAdd.setText("-");

        btnStudentSearch.setText("Consultar");
        btnStudentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSearchActionPerformed(evt);
            }
        });

        tbDataEnrollments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDataEnrollments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataEnrollmentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDataEnrollments);

        tbDataCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDataCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataCoursesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDataCourses);

        lblTitle1.setText("Cursos matriculados");

        lblTitle2.setText("Cursos");

        lblTitle3.setText("Curso seleccionado");

        lblCourseTitleAdd.setText("-");

        lblCourseTitle.setText("Nombre:");

        btnCourseAdd.setText(">");
        btnCourseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseAddActionPerformed(evt);
            }
        });

        btnCourseRemove.setText("<");
        btnCourseRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseRemoveActionPerformed(evt);
            }
        });

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCourseIdAdd.setText(".");

        lblStudentIdAdd.setText(".");

        lblEnrollmentId.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStudentCode)
                                .addGap(18, 18, 18)
                                .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStudentSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudentFullName)
                                    .addComponent(lblStudentEnrollmentDate))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblStudentFullNameAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(lblStudentEnrollmentDateAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTitle3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCourseIdAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEnrollmentId))
                                    .addComponent(btnCourseAdd)
                                    .addComponent(btnCourseRemove)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCourseTitle)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCourseTitleAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblStudentIdAdd))))
                    .addComponent(lblTitle1)
                    .addComponent(lblTitle2))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentCode)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentSearch)
                    .addComponent(btnBack)
                    .addComponent(lblStudentIdAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentFullName)
                    .addComponent(lblStudentFullNameAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentEnrollmentDate)
                    .addComponent(lblStudentEnrollmentDateAdd))
                .addGap(18, 18, 18)
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle3)
                            .addComponent(lblCourseIdAdd)
                            .addComponent(lblEnrollmentId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseTitleAdd)
                            .addComponent(lblCourseTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCourseRemove)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSearchActionPerformed

        try {

            Student student = new Student();
            StudentService studentService = new StudentService();

            if (txtStudentId.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar el código del estudiante.");
                return;
            }

            int code = Integer.parseInt(txtStudentId.getText());

            student = studentService.GetById(code);

            if (student.getId() == 0) {
                JOptionPane.showMessageDialog(rootPane, "No se encontraron registros.");
                tbDataEnrollments.setModel(new DefaultTableModel());
                tbDataCourses.setModel(new DefaultTableModel());
            } else {

                lblStudentIdAdd.setText(String.valueOf(student.getId()));
                lblStudentIdAdd.setVisible(false);

                lblStudentEnrollmentDateAdd.setText(String.valueOf(student.getEnrollmentDate()));

                String fullName = student.getLastName() + " " + student.getFirstMidName();
                lblStudentFullNameAdd.setText(fullName);

                List<Course> coursesEnrollment = new ArrayList<>();
                EnrollmentService enrollmentService = new EnrollmentService();

                coursesEnrollment = enrollmentService.GetCoursesByStudent(code);

                String[] columnsEnrollments = {"Id", "Titulo", "Creditos", "Matricula"};
                DefaultTableModel modelEnrollments = new DefaultTableModel(null, columnsEnrollments);

                String[] rowsEnrollments = new String[4];
                List<Integer> coursesId = new ArrayList<>();

                for (Course item : coursesEnrollment) {

                    rowsEnrollments[0] = String.valueOf(item.getCourseId());
                    rowsEnrollments[1] = item.getTitle();
                    rowsEnrollments[2] = String.valueOf(item.getCredits());
                    rowsEnrollments[3] = String.valueOf(item.getEnrollmentId());

                    modelEnrollments.addRow(rowsEnrollments);
                    coursesId.add(item.getCourseId());
                }

                if (coursesEnrollment.isEmpty()) {
                    tbDataEnrollments.setModel(new DefaultTableModel());
                } else {
                    tbDataEnrollments.setModel(modelEnrollments);
                }

                List<Course> courses = new ArrayList<>();
                CourseService courseService = new CourseService();

                courses = courseService.GetAll();

                String[] columnsCourses = {"Id", "Titulo", "Creditos"};
                DefaultTableModel modelCourses = new DefaultTableModel(null, columnsCourses);

                String[] rowsCourses = new String[3];

                for (Course item : courses) {

                    boolean flag = coursesId.contains(item.getCourseId());

                    if (!flag) {
                        rowsCourses[0] = String.valueOf(item.getCourseId());
                        rowsCourses[1] = item.getTitle();
                        rowsCourses[2] = String.valueOf(item.getCredits());

                        modelCourses.addRow(rowsCourses);
                    }
                }

                if (courses.isEmpty()) {
                    tbDataCourses.setModel(new DefaultTableModel());
                } else {
                    tbDataCourses.setModel(modelCourses);
                }
            }

        } catch (NumberFormatException | SQLException | ClassNotFoundException | HeadlessException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_btnStudentSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        if (this.roleId == 1) {
            MenuStudent menuStudent = new MenuStudent();
            menuStudent.setVisible(true);
        } else {
            Menu menu = new Menu();
            menu.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tbDataEnrollmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataEnrollmentsMouseClicked

        try {

            btnCourseAdd.setEnabled(false);
            btnCourseRemove.setEnabled(true);

            if (evt.getButton() == 1) {
                int row = tbDataEnrollments.getSelectedRow();

                Course course = new Course();
                CourseService courseService = new CourseService();

                course = courseService.GetById(Integer.valueOf(tbDataEnrollments.getValueAt(row, 0).toString()));

                lblCourseIdAdd.setText(String.valueOf(course.getCourseId()));
                lblCourseIdAdd.setVisible(false);
                lblCourseTitleAdd.setText(course.getTitle());
                lblEnrollmentId.setText(tbDataEnrollments.getValueAt(row, 3).toString());
            }
        } catch (NumberFormatException | SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_tbDataEnrollmentsMouseClicked

    private void tbDataCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataCoursesMouseClicked

        try {

            btnCourseRemove.setEnabled(false);
            btnCourseAdd.setEnabled(true);

            if (evt.getButton() == 1) {
                int row = tbDataCourses.getSelectedRow();

                Course course = new Course();
                CourseService courseService = new CourseService();

                course = courseService.GetById(Integer.valueOf(tbDataCourses.getValueAt(row, 0).toString()));

                lblCourseIdAdd.setText(String.valueOf(course.getCourseId()));
                lblCourseIdAdd.setVisible(false);
                lblCourseTitleAdd.setText(course.getTitle());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_tbDataCoursesMouseClicked

    private void btnCourseRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRemoveActionPerformed
        try {

            int enrollmentId = Integer.valueOf(lblEnrollmentId.getText());
            NoteService noteService = new NoteService();
            List<Note> notes = noteService.GetNotes(enrollmentId);

            if (!notes.isEmpty()) {
                throw new Exception("No es posible eliminar el curso matriculado porque posee notas registradas.");
            }

            int courseId = Integer.valueOf(lblCourseIdAdd.getText());
            int studentId = Integer.valueOf(lblStudentIdAdd.getText());

            EnrollmentService enrollmentService = new EnrollmentService();

            enrollmentService.Delete(courseId, studentId);

            btnStudentSearchActionPerformed(evt);
            JOptionPane.showMessageDialog(rootPane, "Se realizo proceso con exito.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnCourseRemoveActionPerformed

    private void btnCourseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseAddActionPerformed
        try {

            int courseId = Integer.valueOf(lblCourseIdAdd.getText());
            int studentId = Integer.valueOf(lblStudentIdAdd.getText());

            EnrollmentService enrollmentService = new EnrollmentService();

            enrollmentService.Create(courseId, studentId);

            btnStudentSearchActionPerformed(evt);
            JOptionPane.showMessageDialog(rootPane, "Se realizo proceso con exito.");

        } catch (NumberFormatException | SQLException | ClassNotFoundException | HeadlessException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnCourseAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enrollments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enrollments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enrollments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enrollments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enrollments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCourseAdd;
    private javax.swing.JButton btnCourseRemove;
    private javax.swing.JButton btnStudentSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseIdAdd;
    private javax.swing.JLabel lblCourseTitle;
    private javax.swing.JLabel lblCourseTitleAdd;
    private javax.swing.JLabel lblEnrollmentId;
    private javax.swing.JLabel lblStudentCode;
    private javax.swing.JLabel lblStudentEnrollmentDate;
    private javax.swing.JLabel lblStudentEnrollmentDateAdd;
    private javax.swing.JLabel lblStudentFullName;
    private javax.swing.JLabel lblStudentFullNameAdd;
    private javax.swing.JLabel lblStudentIdAdd;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JTable tbDataCourses;
    private javax.swing.JTable tbDataEnrollments;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
